name: Build

on: pull_request

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v22.x
      - name: Install and Tests
        run: |
          npm install
          mvn clean install 
          mvn test
