name: Build

on: pull_request

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: List Directory Structure
        run: |
          ls -R
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Ajuste para a versão do Java usada no projeto
          distribution: 'temurin'

      - name: Build Backend with Maven
        working-directory: TO_DO_LIST/todolist-api-main/backend # Navega até o diretório do backend
        run: |
          mvn clean install
          mvn test
