name: CI/CD with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test and Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use o Java necessário para seu projeto
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Navegar até o diretório backend
      - name: Navigate to Backend Directory
        working-directory: todolist-api-main/backend
        run: echo "Navigated to backend directory"

      # Build e Testes
      - name: Build and Test
        working-directory: todolist-api-main/backend
        run: mvn clean install

      # Setup do Sonar Scanner
      - name: Download and setup Sonar Scanner
        working-directory: todolist-api-main/backend
        run: |
          curl -sL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip -d $HOME/.sonar-scanner
          echo "export PATH=\$PATH:\$HOME/.sonar-scanner/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_ENV

      # Análise SonarQube
      - name: SonarQube Analysis
        working-directory: todolist-api-main/backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=TesteToDoList \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
